### ISSUE TITLE
Create OpenLMIS API end-points

### ISSUE THREAD

**Issue by vincent-karuri** [OpenSRP/opensrp-server-openlmis#5]
- [x] Implement TradeItem /get end-point to get a list of all TradeItems
- [x] Implement CommodityType /get end-point to get a list of all CommodityTypes
- [x] Implement Program /get end-point to get a list of all Programs
- [x] Implement Orderable /get end-point to get a list of all Orderables
- [x] Implement ProgramOrderables /get end-point to get a list of all ProgramOrderables
- [x] Implement Lot /get end-point to get a list of all Lots
- [x] Implement Reason /get end-point to get a list of all Reasons
- [x] Implement  Location /get end-point to get a list of all Locations specific to a user
- [x] Implement TradeItemClassification /get end-point to get a list of all TradeItemClassifications
- [x] Implement TradeItem /add end-point to post new TradeItems
- [x] Implement CommodityType /add end-point to post new CommodityTypes
- [x] Implement Program /add end-point to post new Programs
- [x] Implement Orderable /add end-point to post new Orderables
- [x] Implement Lot /add end-point to post new Lots
- [x] Implement Reason /add end-point to post new Reasons
- [x] Implement ProgramOrderable /add end-point to post new ProgramOrderables
- [x] Implement TradeItemClassification /add end-point to post new TradeItemClassifications
- [x] Implement TradeItem /sync end-point to sync TradeItems by server version 
- [x] Implement CommodityType /sync end-point to sync CommodityTypes by server version 
- [x] Implement Program /sync end-point sync Programs by server version 
- [x] Implement Orderable /sync end-point sync Orderables by server version 
- [x] Implement ProgramOrderable /sync end-point sync ProgramOrderables by server version 
- [x] Implement  Lot /sync end-point to get a list of all Lot by server version
- [x] Implement  Reason /sync end-point to get a list of all Reasons by server version
- [x] Implement TradeItemClassification /sync end-point to sync TradeItemClassifications by server version 
- [x] Implement TradeItem /update end-point to update existing TradeItems
- [x] Implement CommodityType  /update end-point to update existing  CommodityTypes
- [x] Implement Program  /update end-point to update existing  Programs
- [x] Implement Orderable  /update end-point to update existing  Orderables
- [x] Implement Lot  /update end-point to update existing  Lots
- [x] Implement Reason  /update end-point to update existing  Reasons
- [x] Implement ProgramOrderable  /update end-point to update existing  ProgramOrderables
- [x] Implement TradeItemClassification  /update end-point to update existing  TradeItemClassifications
- [x] Add tests
- [x] Add required files for war file build

**Comment by githengi** [comment]
- [ ] On the master_table the server version in JSON is 0, while the one in the server_version column is different.
- [ ] GET and sync endpoints returns server version 0 for the trade-items
- [ ] For server_version use System.currentTimeMillis() instead of System.nanoTime(). System.nanoTime() is based on random reference and invocation in different thread will result in different values(Its not thread safe)
